name: Deploy BookStack to EC2

on:
  push:
    branches:
      - development 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 18.208.251.201
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ubuntu/bookstack-deploy"

    - name: SSH and deploy on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 18.208.251.201
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/bookstack-deploy
          docker-compose down
          docker-compose up -d --build

